name: base
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=23.1.0
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=38.0.4
  - idna=3.4
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1s
  - pip=22.3.1
  - pluggy=1.0.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python.app=3
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstandard=0.18.0
  - pip:
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.0
      - np==1.24.2
      - packaging==23.0
      - pillow==9.4.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - scipy==1.10.1
prefix: /Users/baoc/miniconda3
